/**
 *
 * Copyright 2006 (C) The original author or authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.livetribe.arm.connection.hibernate;

import org.opengroup.arm40.transaction.ArmUser;

import org.livetribe.arm.connection.Connection;


/**
 * @version $Revision$ $Date$
 */
public class HybernateConnection implements Connection
{
    public void declareIdentityProperties(String idPropOID, String[] idNames, String[] idValues, String[] ctxNames)
    {
        //todo: consider this autogenerated code
    }

    public void declareIdentityPropertiesTransaction(String idPropOID, String[] idNames, String[] idValues, String[] ctxNames, String uriValue)
    {
        //todo: consider this autogenerated code
    }

    public void declareApplicationDefinition(String appDefOID, String name, String idPropOID, byte[] id)
    {
        //todo: consider this autogenerated code
    }

    public void declareApplication(String appOID, String appDefOID, String group, String instance, String[] contextValues)
    {
        //todo: consider this autogenerated code
    }

    public void declareApplicationRemote(String appOID, String appDefOID, String group, String instance, String[] contextValues, byte[] systemAddress)
    {
        //todo: consider this autogenerated code
    }

    public void declareTransactionDefinition(String transDefOID, String name, String[] idNames, String[] idValues, String[] ctxNames, String uri, byte[] id)
    {
        //todo: consider this autogenerated code
    }

    public void associateTransaction(String transOID, String appOID, String transDefOID)
    {
        //todo: consider this autogenerated code
    }

    public void introduceMetricGroupDefinition(String metricGroupDefOID, String[] appDef, String[] name, String[] units, short[] usage, byte[][]id)
    {
        //todo: consider this autogenerated code
    }

    public void start(String transOID, byte[] correlator, long start, byte[] parent, ArmUser user, String[] contextValues, String contextURI)
    {
        //todo: consider this autogenerated code
    }

    public void update(String transOID, byte[] correlator, long ts)
    {
        //todo: consider this autogenerated code
    }

    public void block(String transOID, byte[] correlator, long handle, long ts)
    {
        //todo: consider this autogenerated code
    }

    public void unblocked(String transOID, byte[] correlator, long handle, long ts)
    {
        //todo: consider this autogenerated code
    }

    public void stop(String transOID, byte[] correlator, long end, int status, String message)
    {
        //todo: consider this autogenerated code
    }

    public void reset(String transOID, byte[] correlator)
    {
        //todo: consider this autogenerated code
    }

    public void start()
    {
        //todo: consider this autogenerated code
    }

    public void stop()
    {
        //todo: consider this autogenerated code
    }

    public void close()
    {
        //todo: consider this autogenerated code
    }
}
