/**
 *
 * Copyright 2006 (C) The original author or authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.livetribe.arm.transaction;

import org.opengroup.arm40.transaction.ArmApplication;
import org.opengroup.arm40.transaction.ArmApplicationDefinition;
import org.opengroup.arm40.transaction.ArmCorrelator;
import org.opengroup.arm40.transaction.ArmErrorCallback;
import org.opengroup.arm40.transaction.ArmID;
import org.opengroup.arm40.transaction.ArmIdentityProperties;
import org.opengroup.arm40.transaction.ArmIdentityPropertiesTransaction;
import org.opengroup.arm40.transaction.ArmTransaction;
import org.opengroup.arm40.transaction.ArmTransactionDefinition;
import org.opengroup.arm40.transaction.ArmTransactionFactory;
import org.opengroup.arm40.transaction.ArmUser;

import org.livetribe.arm.LTAbstractFactoryBase;
import org.livetribe.arm.util.LTProxyFactory;


/**
 * @version $Revision: $ $Date: $
 */
public class LTTransactionFactory extends LTAbstractFactoryBase implements ArmTransactionFactory
{
    public ArmApplication newArmApplication(ArmApplicationDefinition definition, String group, String instance, String[] contextValues)
    {
        return null;  //todo: consider this autogenerated code
    }

    public ArmApplicationDefinition newArmApplicationDefinition(String name, ArmIdentityProperties identityProperties, ArmID id)
    {
        return null;  //todo: consider this autogenerated code
    }

    public ArmCorrelator newArmCorrelator(byte[] corrBytes)
    {
        return null;  //todo: consider this autogenerated code
    }

    public ArmCorrelator newArmCorrelator(byte[] corrBytes, int offset)
    {
        return null;  //todo: consider this autogenerated code
    }

    public ArmID newArmID(byte[] idBytes)
    {
        return null;  //todo: consider this autogenerated code
    }

    public ArmID newArmID(byte[] idBytes, int offset)
    {
        return null;  //todo: consider this autogenerated code
    }

    public ArmIdentityProperties newArmIdentityProperties(String[] identityNames, String[] identityValues, String[] contextNames)
    {
        return (ArmIdentityProperties) LTProxyFactory.newProxyInstance(new LTIdentityProperties(this, identityNames, identityValues, contextNames));
    }

    public ArmIdentityPropertiesTransaction newArmIdentityPropertiesTransaction(String[] identityNames, String[] identityValues, String[] contextNames, String uriValue)
    {
        return (ArmIdentityPropertiesTransaction) LTProxyFactory.newProxyInstance(new LTIdentityPropertiesTransaction(this, identityNames, identityValues, contextNames, uriValue));
    }

    public ArmTransaction newArmTransaction(ArmApplication app, ArmTransactionDefinition definition)
    {
        return null;  //todo: consider this autogenerated code
    }

    public ArmTransactionDefinition newArmTransactionDefinition(ArmApplicationDefinition app, String name, ArmIdentityPropertiesTransaction identityProperties, ArmID id)
    {
        return null;  //todo: consider this autogenerated code
    }

    public ArmUser newArmUser(String name, ArmID id)
    {
        return null;  //todo: consider this autogenerated code
    }

    public boolean setErrorCallback(ArmErrorCallback errorCallback)
    {
        return false;  //todo: consider this autogenerated code
    }
}
