/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_livetribe_jmxcpu_Win32ProcessorUsage */

#ifndef _Included_org_livetribe_jmxcpu_Win32ProcessorUsage
#define _Included_org_livetribe_jmxcpu_Win32ProcessorUsage
#ifdef __cplusplus
extern "C" {
#endif
#undef org_livetribe_jmxcpu_Win32ProcessorUsage_USER_INDEX
#define org_livetribe_jmxcpu_Win32ProcessorUsage_USER_INDEX 0L
#undef org_livetribe_jmxcpu_Win32ProcessorUsage_SYSTEM_INDEX
#define org_livetribe_jmxcpu_Win32ProcessorUsage_SYSTEM_INDEX 1L
#undef org_livetribe_jmxcpu_Win32ProcessorUsage_IDLE_INDEX
#define org_livetribe_jmxcpu_Win32ProcessorUsage_IDLE_INDEX 2L
/*
 * Class:     org_livetribe_jmxcpu_Win32ProcessorUsage
 * Method:    getProcessorSnapshot
 * Signature: ()[J
 */
JNIEXPORT jlongArray JNICALL Java_org_livetribe_jmxcpu_Win32ProcessorUsage_getProcessorSnapshot
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
