/**
 *
 * Copyright 2006 (C) The original author or authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.livetribe.arm.ra.activemq;

import org.livetribe.arm.connection.ConnectionFactory;
import org.livetribe.arm.connection.Connection;
import org.livetribe.arm.connection.ConnectionException;


/**
 * @version $Revision: $ $Date$
 */
public class ActiveMQConnectionFactory implements ConnectionFactory
{
    public Connection createConnection() throws ConnectionException
    {
        return null;  //todo: consider this autogenerated code
    }

    public Connection createConnection(String userName, String password) throws ConnectionException
    {
        return null;  //todo: consider this autogenerated code
    }
}
