/**
 *
 * Copyright 2006 (C) The original author or authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.livetribe.arm40.ra.hibernate;

import javax.resource.ResourceException;
import javax.resource.spi.ConnectionManager;
import javax.resource.spi.ConnectionRequestInfo;
import javax.resource.spi.ManagedConnection;
import javax.resource.spi.ManagedConnectionFactory;
import javax.resource.spi.ResourceAdapter;
import javax.resource.spi.ResourceAdapterAssociation;
import javax.security.auth.Subject;
import java.io.PrintWriter;
import java.util.Set;


/**
 * @version $Revision$ $Date$
 */
public class HibernateManagedConnectionFactory implements ManagedConnectionFactory, ResourceAdapterAssociation
{
    private PrintWriter logWriter;
    private HibernateResourceAdapter resourceAdapter;

    public Object createConnectionFactory(ConnectionManager connectionManager) throws ResourceException
    {
        return null;  //todo: consider this autogenerated code
    }

    public Object createConnectionFactory() throws ResourceException
    {
        return null;  //todo: consider this autogenerated code
    }

    public ManagedConnection createManagedConnection(Subject subject, ConnectionRequestInfo connectionRequestInfo) throws ResourceException
    {
        return null;  //todo: consider this autogenerated code
    }

    public ManagedConnection matchManagedConnections(Set set, Subject subject, ConnectionRequestInfo connectionRequestInfo) throws ResourceException
    {
        return null;  // todo: consider this autogenerated code
    }

    public void setLogWriter(PrintWriter logWriter) throws ResourceException
    {
        this.logWriter = logWriter;
    }

    public PrintWriter getLogWriter() throws ResourceException
    {
        return logWriter;
    }

    public ResourceAdapter getResourceAdapter()
    {
        return resourceAdapter;
    }

    public void setResourceAdapter(ResourceAdapter resourceAdapter) throws ResourceException
    {
        this.resourceAdapter = (HibernateResourceAdapter) resourceAdapter;
    }
}
