/**
 *
 * Copyright 2006 (C) The original author or authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.livetribe.arm40.ra.hibernate;

import java.util.List;

import org.livetribe.arm40.connection.Connection;


/**
 * @version $Revision$ $Date$
 */
public class HibernateConnection implements Connection
{
    public void declareIdentityProperties(String idPropOID, String[] idNames, String[] idValues, String[] ctxNames)
    {
        //todo: consider this autogenerated code
    }

    public void declareIdentityPropertiesTransaction(String idPropOID, String[] idNames, String[] idValues, String[] ctxNames, String uriValue)
    {
        //todo: consider this autogenerated code
    }

    public void declareApplicationDefinition(String appDefOID, String name, String idPropOID, byte[] id)
    {
        //todo: consider this autogenerated code
    }

    public void declareApplication(String appOID, String appDefOID, String group, String instance, String[] contextValues)
    {
        //todo: consider this autogenerated code
    }

    public void declareApplicationRemote(String appOID, String appDefOID, String group, String instance, String[] contextValues, byte[] systemAddress)
    {
        //todo: consider this autogenerated code
    }

    public void declareTransactionDefinition(String transDefOID, String name, String idPropTranOID, byte[] id)
    {
        //todo: consider this autogenerated code
    }

    public void associateTransaction(String transOID, String appOID, String transDefOID)
    {
        //todo: consider this autogenerated code
    }

    public void declareTranReport(String tranReportOID, String appOID, String tranDefOID)
    {
        //todo: consider this autogenerated code
    }

    public void declareMetricCounter32Definition(String metricDefOID, String appDefOID, String name, String units, short usage, byte[] id)
    {
        //todo: consider this autogenerated code
    }

    public void declareMetricCounter64Definition(String metricDefOID, String appDefOID, String name, String units, short usage, byte[] id)
    {
        //todo: consider this autogenerated code
    }

    public void declareMetricCounterFloat32Definition(String metricDefOID, String appDefOID, String name, String units, short usage, byte[] id)
    {
        //todo: consider this autogenerated code
    }

    public void declareMetricGauge32Definition(String metricDefOID, String appDefOID, String name, String units, short usage, byte[] id)
    {
        //todo: consider this autogenerated code
    }

    public void declareMetricGauge64Definition(String metricDefOID, String appDefOID, String name, String units, short usage, byte[] id)
    {
        //todo: consider this autogenerated code
    }

    public void declareMetricGaugeFloat32Definition(String metricDefOID, String appDefOID, String name, String units, short usage, byte[] id)
    {
        //todo: consider this autogenerated code
    }

    public void declareMetricNumericId32Definition(String metricDefOID, String appDefOID, String name, String units, short usage, byte[] id)
    {
        //todo: consider this autogenerated code
    }

    public void declareMetricNumericId64Definition(String metricDefOID, String appDefOID, String name, String units, short usage, byte[] id)
    {
        //todo: consider this autogenerated code
    }

    public void declareMetricString32Definition(String metricDefOID, String appDefOID, String name, String units, short usage, byte[] id)
    {
        //todo: consider this autogenerated code
    }

    public void declareMetricGroupDefinition(String metricGroupDefOID, String[] metricDefOIDs)
    {
        //todo: consider this autogenerated code
    }

    public void declareTransactionWithMetricsDefinition(String transDefOID, String appDefOID, String name, String idPropOID, String metricGroupDefOID, byte[] id)
    {
        //todo: consider this autogenerated code
    }

    public void declareMetricGroup(String metricGroupOID, String metricGroupDefOID)
    {
        //todo: consider this autogenerated code
    }

    public void declareTranReportWithMetrics(String tranReportMetricsOID, String tranReportMetricsDefOID, String metricGroupOID)
    {
        //todo: consider this autogenerated code
    }

    public void declareTranWithMetrics(String tranMetricsOID, String tranReportMetricsDefOID, String metricGroupOID)
    {
        //todo: consider this autogenerated code
    }

    public void stop(String transOID, byte[] correlator, long end, int status, String message)
    {
        //todo: consider this autogenerated code
    }

    public void start(String transOID, byte[] correlator, long start, byte[] parent, String user, String[] contextValues, String contextURI)
    {
        //todo: consider this autogenerated code
    }

    public void update(String transOID, byte[] correlator, long ts)
    {
        //todo: consider this autogenerated code
    }

    public void block(String transOID, byte[] correlator, long handle, long ts)
    {
        //todo: consider this autogenerated code
    }

    public void unblocked(String transOID, byte[] correlator, long handle, long ts)
    {
        //todo: consider this autogenerated code
    }

    public void stop(String transOID, byte[] correlator, long end, int status, String message, List[] metrics)
    {
        //todo: consider this autogenerated code
    }

    public void reset(String transOID, byte[] correlator)
    {
        //todo: consider this autogenerated code
    }

    public void report(String reportOID, byte[] parent, byte[] correlator, int status, long respTime, String diagnosticDetail)
    {
        //todo: consider this autogenerated code
    }

    public void report(String reportOID, byte[] parent, byte[] correlator, int status, long respTime, long stopTime, String diagnosticDetail)
    {
        //todo: consider this autogenerated code
    }

    public void report(String reportOID, byte[] parent, byte[] correlator, int status, long respTime, String diagnosticDetail, List[] metrics)
    {
        //todo: consider this autogenerated code
    }

    public void report(String reportOID, byte[] parent, byte[] correlator, int status, long respTime, long stopTime, String diagnosticDetail, List[] metrics)
    {
        //todo: consider this autogenerated code
    }

    public void start()
    {
        //todo: consider this autogenerated code
    }

    public void stop()
    {
        //todo: consider this autogenerated code
    }

    public void close()
    {
        //todo: consider this autogenerated code
    }
}
