/**
 *
 * Copyright 2006 (C) The original author or authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.livetribe.arm40.ra.hibernate;

import javax.naming.NamingException;
import javax.naming.Reference;
import javax.resource.Referenceable;
import java.io.Serializable;

import org.livetribe.arm40.connection.Connection;
import org.livetribe.arm40.connection.ConnectionException;
import org.livetribe.arm40.connection.ConnectionFactory;


/**
 * @version $Revision$ $Date$
 */
public class HibernateConnectionFactory implements ConnectionFactory, Referenceable, Serializable
{
    private Reference reference;

    public Connection createConnection() throws ConnectionException
    {
        return null;  //todo: consider this autogenerated code
    }

    public Connection createConnection(String userName, String password) throws ConnectionException
    {
        return null;  //todo: consider this autogenerated code
    }

    public void setReference(Reference reference)
    {
        this.reference = reference;
    }

    public Reference getReference() throws NamingException
    {
        return reference;
    }
}
