/**
 *
 * Copyright 2007 (C) The original author or authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.livetribe.boot.beep;

import net.sf.beep4j.Message;
import net.sf.beep4j.ResponseHandler;
import net.sf.beep4j.ext.ChannelHandlerAdapter;
import org.livetribe.boot.protocol.BootServer;

/**
 * @version $Revision$ $Date$
 */
public class ServeChannelHandler extends ChannelHandlerAdapter
{
    private final BootServer bootServer;

    public ServeChannelHandler(BootServer bootServer)
    {
        this.bootServer = bootServer;
    }

    public void messageReceived(Message message, ResponseHandler responseHandler)
    {
        responseHandler.sendANS(null);
        //todo: consider this autogenerated code
    }
}
