/**
 *
 * Copyright 2006 (C) The original author or authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.livetribe.arm.util;

import java.net.URL;
import java.net.URLClassLoader;
import java.util.Enumeration;
import java.io.IOException;


/**
 * @version $Revision: $ $Date$
 */
public class ArmClassLoader extends URLClassLoader
{
    private final ClassLoader fallback;

    public ArmClassLoader(URL[] urls, ClassLoader fallback)
    {
        super(urls);
        this.fallback = fallback;
    }

    public Class loadClass(String name) throws ClassNotFoundException
    {
        return super.loadClass(name);    //todo: consider this autogenerated code
    }

    public URL getResource(String name)
    {
        return super.getResource(name);    //todo: consider this autogenerated code
    }
}
