/**
 *
 * Copyright 2006 (C) The original author or authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.livetribe.arm.impl;

import org.opengroup.arm40.transaction.ArmApplicationDefinition;
import org.opengroup.arm40.transaction.ArmID;
import org.opengroup.arm40.transaction.ArmIdentityProperties;

import org.livetribe.arm.LTAbstractObject;


/**
 * @version $Revision: $ $Date: $
 */
class LTApplicationDefinition extends LTAbstractObject implements ArmApplicationDefinition
{
    private final String name;
    private final LTIdentityProperties identityProperties;
    private final ArmID id;

    LTApplicationDefinition(String name, ArmIdentityProperties identityProperties, ArmID id)
    {
        this.name = name;
        this.identityProperties = (LTIdentityProperties) identityProperties;
        this.id = id;
    }

    public void destroy()
    {
        //todo: consider this autogenerated code
    }

    public String getName()
    {
        return name;
    }

    public ArmIdentityProperties getIdentityProperties()
    {
        return identityProperties;
    }

    public ArmID getID()
    {
        return id;
    }
}
