/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_livetribe_net_RawPacket */

#ifndef _Included_org_livetribe_net_RawPacket
#define _Included_org_livetribe_net_RawPacket
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_livetribe_net_RawPacket
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_livetribe_net_RawPacket_init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
