/**
 *
 * Copyright 2006 (C) The original author or authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package javax.script;

import java.io.Reader;


/**
 * @version $Revision: $ $Date$
 */
public abstract class GenericScriptEngine implements ScriptEngine
{
    public Object eval(String script) throws ScriptException
    {
        return null;  //todo: consider this autogenerated code
    }

    public Object eval(Reader reader) throws ScriptException
    {
        return null;  //todo: consider this autogenerated code
    }

    public Object eval(String script, Namespace namespace) throws ScriptException
    {
        return null;  //todo: consider this autogenerated code
    }

    public Object eval(Reader reader, Namespace namespace) throws ScriptException
    {
        return null;  //todo: consider this autogenerated code
    }

    public Object get(String key)
    {
        return null;  //todo: consider this autogenerated code
    }

    public Namespace getNamespace(int scope)
    {
        return null;  //todo: consider this autogenerated code
    }

    public void setNamespace(Namespace namespace, int scope)
    {
        //todo: consider this autogenerated code
    }

    public Namespace createNamespace()
    {
        return null;  //todo: consider this autogenerated code
    }

    public ScriptContext getContext()
    {
        return null;  //todo: consider this autogenerated code
    }

    public void setContext(ScriptContext context)
    {
        //todo: consider this autogenerated code
    }

    public ScriptEngineFactory getFactory()
    {
        return null;  //todo: consider this autogenerated code
    }
}
