/**
 *
 * Copyright 2006 (C) The original author or authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.livetribe.arm.ra.hibernate;

import javax.resource.spi.work.Work;


/**
 * @version $Revision$ $Date$
 */
class EndpointWorker implements Work
{
    protected final HibernateResourceAdapter adapter;
    protected final EndpointActivationKey endpointActivationKey;
    protected boolean running = false;

    EndpointWorker(HibernateResourceAdapter adapter, EndpointActivationKey endpointActivationKey)
    {
        this.adapter = adapter;
        this.endpointActivationKey = endpointActivationKey;
    }

    public void release()
    {
        if (!running) return;

        running = false;
    }

    public void run()
    {
        //todo: consider this autogenerated code

        adapter.countDown();
    }
}
