/**
 *  Copyright 2006 Simula Labs Inc., 4676 Admiralty Way, Suite 520 Marina del Rey, CA 90292 U.S.A. All rights reserved.
 */
package org.livetribe.arm.ra.hibernate;

import javax.transaction.xa.XAResource;
import javax.transaction.xa.Xid;
import javax.transaction.xa.XAException;


/**
 * @version $Revision$ $Date$
 */
public class HibernateXAResource implements XAResource
{
    public void commit(Xid xid, boolean onePhase) throws XAException
    {
        //todo: consider this autogenerated code
    }

    public void end(Xid xid, int flags) throws XAException
    {
        //todo: consider this autogenerated code
    }

    public void forget(Xid xid) throws XAException
    {
        //todo: consider this autogenerated code
    }

    public int getTransactionTimeout() throws XAException
    {
        return 0;  //todo: consider this autogenerated code
    }

    public boolean isSameRM(XAResource xares) throws XAException
    {
        return false;  //todo: consider this autogenerated code
    }

    public int prepare(Xid xid) throws XAException
    {
        return 0;  //todo: consider this autogenerated code
    }

    public Xid[] recover(int flag) throws XAException
    {
        return new Xid[0];  //todo: consider this autogenerated code
    }

    public void rollback(Xid xid) throws XAException
    {
        //todo: consider this autogenerated code
    }

    public boolean setTransactionTimeout(int seconds) throws XAException
    {
        return false;  //todo: consider this autogenerated code
    }

    public void start(Xid xid, int flags) throws XAException
    {
        //todo: consider this autogenerated code
    }
}
