/**
 *
 * Copyright 2006 (C) The original author or authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.livetribe.arm.ra.hibernate;

import javax.resource.ResourceException;
import javax.resource.spi.ActivationSpec;
import javax.resource.spi.InvalidPropertyException;
import javax.resource.spi.ResourceAdapter;
import java.io.Serializable;


/**
 * @version $Revision$ $Date$
 */
public class HibernateActivationSpec implements ActivationSpec, Serializable
{
    private ResourceAdapter resourceAdapter;

    public void validate() throws InvalidPropertyException
    {
        //todo: consider this autogenerated code
    }

    public ResourceAdapter getResourceAdapter()
    {
        return resourceAdapter;
    }

    public void setResourceAdapter(ResourceAdapter resourceAdapter) throws ResourceException
    {
        if (this.resourceAdapter != null) throw new ResourceException("ResourceAdapter already set");

        if (!(resourceAdapter instanceof HibernateResourceAdapter))
            throw new ResourceException("ResourceAdapter is not of type: " + HibernateResourceAdapter.class.getName());

        this.resourceAdapter = resourceAdapter;
    }
}
