/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_livetribe_net_util_Util */

#ifndef _Included_org_livetribe_net_util_Util
#define _Included_org_livetribe_net_util_Util
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_livetribe_net_util_Util
 * Method:    uncheckedChecksum
 * Signature: ([BII)S
 */
JNIEXPORT jshort JNICALL Java_org_livetribe_net_util_Util_uncheckedChecksum
  (JNIEnv *, jclass, jbyteArray, jint, jint);

/*
 * Class:     org_livetribe_net_util_Util
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_livetribe_net_util_Util_init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
