#ifndef LIVETRIBE_EXPORT_H
#define LIVETRIBE_EXPORT_H

#if defined (LIVETRIBE_AS_STATIC_LIBS)

# if !defined (LIVETRIBE_HAS_DLL)
#   define LIVETRIBE_HAS_DLL 0
# endif /* ! LIVETRIBE_HAS_DLL */
#else
# if !defined (LIVETRIBE_HAS_DLL)
#   define LIVETRIBE_HAS_DLL 1
# endif /* ! LIVETRIBE_HAS_DLL */
#endif /* LIVETRIBE_AS_STATIC_LIBS */

#if defined (LIVETRIBE_HAS_DLL)
#  if (LIVETRIBE_HAS_DLL == 1)
#    if defined (LIVETRIBE_BUILD_DLL)
#      define LIVETRIBE_Export ACE_Proper_Export_Flag
#      define LIVETRIBE_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#      define LIVETRIBE_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#    else
#      define LIVETRIBE_Export ACE_Proper_Import_Flag
#      define LIVETRIBE_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#      define LIVETRIBE_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#    endif /* LIVETRIBE_BUILD_DLL */
#  else
#    define LIVETRIBE_Export
#    define LIVETRIBE_SINGLETON_DECLARATION(T)
#    define LIVETRIBE_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif   /* ! LIVETRIBE_HAS_DLL == 1 */
#else
#  define LIVETRIBE_Export
#  define LIVETRIBE_SINGLETON_DECLARATION(T)
#  define LIVETRIBE_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif     /* LIVETRIBE_HAS_DLL */

#endif     /* LIVETRIBE_EXPORT_H */
