/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_livetribe_net_ICMPPacket */

#ifndef _Included_org_livetribe_net_ICMPPacket
#define _Included_org_livetribe_net_ICMPPacket
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_livetribe_net_icmp_ICMPPacket
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_livetribe_net_icmp_ICMPPacket_init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
