/**
 *
 * Copyright 2007-2009 (C) The original author or authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.livetribe.boot.mock.client;

import java.io.InputStream;
import java.net.URL;

import org.livetribe.boot.client.ProvisionConfiguration;
import org.livetribe.boot.client.ProvisionStore;
import org.livetribe.boot.client.ProvisionStoreException;
import org.livetribe.boot.protocol.ProvisionEntry;


/**
 * @version $Revision$ $Date$
 */
public class MockProvisionStore implements ProvisionStore
{
    public String getUuid() throws ProvisionStoreException
    {
        return null;  //todo: consider this autogenerated code
    }

    public void setUuid(String uuid) throws ProvisionStoreException
    {
        //todo: consider this autogenerated code
    }

    public ProvisionConfiguration getCurrentProvisionDirective() throws ProvisionStoreException
    {
        return null;  //todo: consider this autogenerated code
    }

    public ProvisionConfiguration getNextProvisionDirective() throws ProvisionStoreException
    {
        return null;  //todo: consider this autogenerated code
    }

    public void setNextProvisionDirective(ProvisionConfiguration provisionConfiguration) throws ProvisionStoreException
    {
        //todo: consider this autogenerated code
    }

    public void store(ProvisionEntry provisionEntry, InputStream inputStream) throws ProvisionStoreException
    {
        //todo: consider this autogenerated code
    }

    public void prepareNext() throws ProvisionStoreException
    {
        //todo: consider this autogenerated code
    }

    public void commitNext()
    {
        //Todo: change body of implemented methods use File | Settings | File Templates.
    }

    public void rollbackNext()
    {
        //Todo: change body of implemented methods use File | Settings | File Templates.
    }

    public URL[] getClasspath() throws ProvisionStoreException
    {
        return null;  //todo: consider this autogenerated code
    }
}
